# Generated by Django 5.2.4 on 2025-07-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biruk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='title',
            new_name='name',
        ),
    ]
